### PR TITLE
Adding a Project directory and a simple beginner friendly project.

### PR DESCRIPTION
**Pull request by NishantWankhade**
I hope it is ok to have projects for beginners and hence added a project.
Please merge it, and if something is need to be added please let me know. :)
Thank .

### CODE REVIEW

**Comment by NishantWankhade** [comment]
@microsoft-github-policy-service agree [company="{}"]

**Comment by NishantWankhade** [comment]
@microsoft-github-policy-service agree [company="{default}"]

**Comment by NishantWankhade** [comment]
@microsoft-github-policy-service agree

**Comment by jimbobbennett** [comment]
Sorry - this is not the right project to add these projects to. Closing this PR.

**Pull request closed without merging**
