### PR TITLE
clean-up.es.md translation

### PR DESCRIPTION
**Pull request by osfprieto**
FHL

### CODE REVIEW

**Comment by jimbobbennett** [comment]
Thanks @osfprieto. Any reason that this can't be a Spanish translation (es) rather than than Columbian Spanish (es-CO)?

I don't speak Spanish, so can't comment on any linguistic differences between the to variants.

**Review by FMartull — DISMISSED** [review]
Hello, I am from Spain and @osfprieto translation is perfectly understandable. There are a few nuances that I would of said different, but I perfectly understand. I guess that a brit in the US experiences similar situations all the time, right? ;-) 

The translation is perfect.

**Comment by osfprieto** [comment]
Hey @jimbobbennett, just as @FMartull described, it could most likely be es-ES as well.

Me being es-CO native just wanted to not worry about missing slang or variations between cultures.

And I also tend to have a bias towards Colombian Spanish focused resources :)

I've just updated the name of the file to drop the culture modifier.

BTW, it's Colombia, not Columbia.

**Comment by jimbobbennett** [comment]
Thanks @osfprieto and I apologies for the misspelling.

**Review by jimbobbennett — APPROVED** [review]

**Pull request merged**
