### PR TITLE
Create README.hi.md

### PR DESCRIPTION
**Pull request by AdityaGarg00**

### CODE REVIEW

**Review by Anurag-0-1-A — APPROVED** [review]

**Review by jimbobbennett — APPROVED** [review]

**Comment by jimbobbennett** [comment]
@AdityaGarg00 - I've approved these changes based off @Anurag-0-1-A's approval, but I can't 'see' the changes to be able to merge them. Can you change your fork to be public please so I can merge.

**Comment by jimbobbennett** [comment]
@AdityaGarg00 - I've approved these changes based off @Anurag-0-1-A's approval, but I can't 'see' the changes to be able to merge them. Can you change your fork to be public please so I can merge.

**Comment by AdityaGarg00** [comment]
I opened it @jimbobbennett

**Comment by jimbobbennett** [comment]
Weird - I can't merge this, I just get a spinning circle in the merge options box.

If I look at your repo it no-longer shows as a fork of this one.

Would you be able to re-fork this repo then re-add the changed file and raise a separate PR?

**Review by AdityaGarg00 — COMMENTED** [review]
same is happening with me ill try to do that

**Comment by jimbobbennett** [comment]
I've merged your other PR. I'll close this one, but can you do the same for the other PRs you have open?

**Pull request closed without merging**
