### PR TITLE
[BN Translation] Fixed the .png and .gif file hyperlinks 

### PR DESCRIPTION
**Pull request by Diganta-droid**
Fixed the .png and .gif file hyperlinks of [pi.bn.md](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/1-introduction-to-iot/translations/pi.bn.md) file and [wio-terminal.bn.md](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/1-introduction-to-iot/translations/wio-terminal.bn.md) file.
@jimbobbennett, Could you merge this PR?
#50
-Diganta Majumder
Microsoft Learn Student Ambassador
Bangladesh

### CODE REVIEW

**Review by Jeffrooo — DISMISSED** [review]

**Comment by Iftu119** [comment]
Hi @Diganta-droid - There are certain formatting issues in the[ file](https://github.com/microsoft/IoT-For-Beginners/blob/main/1-getting-started/lessons/1-introduction-to-iot/translations/wio-terminal.bn.md) which need to be fixed. I think you have already noticed them. I actually planned to work on it later. But since you have made an input, can you please update them with this PR ?

**Comment by Diganta-droid** [comment]
Ok @Iftu119 working On it!

**Comment by Diganta-droid** [comment]
@Iftu119 I have fixed [wio-terminal.bn.md](https://github.com/Diganta-droid/IoT-For-Beginners-1/blob/main/1-getting-started/lessons/1-introduction-to-iot/translations/wio-terminal.bn.md) readme formatting issues. Could you check if it's ok now?

**Review by Iftu119 — APPROVED** [review]
Good fixing ! Looks fine to me. 👍

**Review by jimbobbennett — APPROVED** [review]

**Pull request merged**
