### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AdityaGarg00**

### CODE REVIEW

**Comment by jimbobbennett** [comment]
@AdityaGarg00 - I'm not seeing the README file that this is pointing to

**Comment by AdityaGarg00** [comment]
@jimbobbennett It's the very first readme file.

**Comment by jimbobbennett** [comment]
I mean the translations/README.hi.md file that is linked to.

**Comment by AdityaGarg00** [comment]
> I mean the translations/README.hi.md file that is linked to.

I am sorry @jimbobbennett for my late reply but I still didn't get it. Can you please elaborate the issue or give me an insight on what shall i do now?

**Pull request closed without merging**
