### PR TITLE
Quiz App Chinese Translation

### PR DESCRIPTION
**Pull request by jks-liu**
I'll finish it this weekend.

- [x] Class 1 ~ 5
- [x] Class 6 ~ 10
- [x] Class 11 ~ 15
- [x] Class 16 ~ 20
- [x] Class 21 ~ 24
- [x] Final check
- [x] Add quiz app zh-cn support

### CODE REVIEW

**Comment by stevenwsg** [comment]
赞~

**Comment by stevenwsg** [comment]
期待期待~

**Comment by stevenwsg** [comment]
有翻译嘛

**Review by Mireille-T — COMMENTED** [review]
Hello @jks-liu , thank you very much for your translations! Just a couple of questions before approving the PR:

Referring to `quiz-app/src/assets/translations/zh-cn.json`,
- In line 180, perhaps for the English translation we can have `Raspberry Pi` instead of `Raspberry Pis`?
- In line 374, do you think it will be a good idea to offer a translation for 测量 as well, to be consistent with the other two options - maybe either "Measurement" or "Survey"?
- In lines 495 and 531, would `以下` instead of `下面` sound more natural to you?
- In line 931, I don't think `:` is required, right?

This is what I've noticed thus far (I am about halfway through the document), I will continue reviewing later when I can. For now though, let me just say I really like your translation! I think it's nice that you've added the English terms beside the Chinese ones for anything technical, and I am also grateful that you've practically helped us translate the names of every single lesson, thank you! 😄

**Comment by jks-liu** [comment]
@Mireille-T Thanks for your review. Your review is very helpful to making the contents more readable.

**Review by Mireille-T — CHANGES_REQUESTED** [review]
Thanks for the improvements so far @jks-liu !

One more suggestion for the second half of the document:
- In line 1925, unless I am misunderstanding, maybe there's a typo for the English translation of `食物` - it should be `Food` instead of `General`

Everything else looks good to me, and once that change has been made I believe the PR can be merged!

**Comment by jks-liu** [comment]
@Mireille-T Yes, it's a typo. I've fixed it.

**Comment by jks-liu** [comment]
Because some terms are very new, and do not have *standard* Chinese translations. So I list here some of my choices FYI and list some links which inspired me of these terms.

- <https://docs.microsoft.com/zh-cn/azure/iot-fundamentals/iot-glossary>
  * Device Twin: 设备孪生
  * Direct Method: 直接方法
  * IoT Hub: IoT中心
- <https://docs.microsoft.com/zh-cn/learn/paths/create-serverless-applications/>
  * Serverless Application: 无服务器应用程序
- <https://zh.d2l.ai/chapter_computer-vision/bounding-box.html>
  * object detection: 目标检测
  * bounding box: 边界框
- <https://iotatlas.net/zh/glossary/vocabulary/>
  * Actuator: 执行器
- <https://books.google.com/books?id=VM6mDwAAQBAJ&pg=PA275&lpg=PA275>
  * Intents: 意图
  * entities: 实体

**Review by Mireille-T — APPROVED** [review]
@jimbobbennett This PR may now be merged. Thanks again @jks-liu for the valuable help!

**Review by jimbobbennett — APPROVED** [review]

**Comment by jimbobbennett** [comment]
Thanks @jks-liu! and thanks @Mireille-T for the review.

**Pull request merged**
