### PR TITLE
french translation Lesson 2-farm > 2-detect-soil-moisture

### PR DESCRIPTION
**Pull request by IterateMe**
Translation for the lesson 2.2 plus a few corrections along the way.

### CODE REVIEW

**Comment by jimbobbennett** [comment]
@Charma95, @IterateMe - let me know when you are happy for me to merge this!

**Review by Charma95 — APPROVED** [review]
This is good work!

**Review by Charma95 — CHANGES_REQUESTED** [review]
Line 26 of translation/README.fr.md contains <<<<<<<< HEAD refering to previous conflict.

**Comment by jimbobbennett** [comment]
> Line 26 of translation/README.fr.md contains <<<<<<<< HEAD refering to previous conflict.

Let me know once this is resolved correctly so I can merge. Thanks for your contributions!

**Review by Charma95 — CHANGES_REQUESTED** [review]
Line 26 <<<<<<<<< HEAD

**Review by Charma95 — DISMISSED** [review]
Approved with comments

**Review by jimbobbennett — APPROVED** [review]

**Comment by jimbobbennett** [comment]
Merged! Thanks @Charma95 and @IterateMe!

**Pull request merged**
