### PR TITLE
Added iot.gif

### PR DESCRIPTION
**Pull request by mohitjaisal**
- Added iot.gif to readme .md 
- The gif is fully compressed and load very fast

Suggested by @jlooper [Merged PR](https://github.com/microsoft/Data-Science-For-Beginners/pull/221#issuecomment-954939774)

## Before:
image

## After:
image

### CODE REVIEW

**Comment by mohitjaisal** [comment]
@jlooper  @jimbobbennett @Iftu119  please review !!

**Comment by jimbobbennett** [comment]
Love it! Thanks @mohitjaisal.

**Review by jimbobbennett — APPROVED** [review]

**Comment by Iftu119** [comment]
This looks cool @mohitjaisal!  Great ❤️

@jimbobbennett - I guess the link might be broken. My device doesn't show the gif (instead it breaks and the alt text appears). Not sure if it's only happening to me.

**Comment by mohitjaisal** [comment]
@Iftu119 you are right. I don't know but the link is broken it was working perfect on my local machine. Please update the link the gif is in images folder and even you can use this direct image source link👉🏻  https://raw.githubusercontent.com/microsoft/IoT-For-Beginners/main/images/IOT.gif

**Comment by jimbobbennett** [comment]
Fixed! GitHub is case sensitive and the file was IOT.git, but the link in code was iot.gif. Would work in a local markdown preview on a non-case sensitive file system, but not on GitHub.

**Pull request merged**
