### PR TITLE
Add pi-sensor Chinese Simplified translation

### PR DESCRIPTION
**Pull request by knowncold**

### CODE REVIEW

**Review by Mireille-T — CHANGES_REQUESTED** [review]
Thanks for your translation again @knowncold, and sorry this review took some time!

A couple of questions / suggestions:
- In line 7, I think instead of simply `lux`, you could write `勒克斯（lux）`; please advise if that is the wrong translation, but based on some searching it should be correct
- For line 82, the original document used `Cover and uncover the light sensor`, so do you think we should use `与` instead of `或者`?

Thanks again! 😄

**Comment by knowncold** [comment]
Thanks for your review again @Mireille-T !
I've fixed line 82 and the same translation in pi-actuator.zh-cn.md.
As for lux, I thought  it's common to use original  unit of measurement, so I didn't translate it.😂

**Review by Mireille-T — APPROVED** [review]
Oh I see, I appreciate you adding it in though, sorry if it was any trouble! Thanks again @knowncold, and @jimbobbennett this PR may now be merged! 😄

**Review by jimbobbennett — APPROVED** [review]

**Comment by jimbobbennett** [comment]
Merged! Thanks @knowncold and @Mireille-T

**Pull request merged**
