### PR TITLE
Add "1-getting-started" chinese translate

### PR DESCRIPTION
**Pull request by NeroBlackstone**

### CODE REVIEW

**Comment by jimbobbennett** [comment]
@Mireille-T has been running our Chinese translations. Mireille - can you review this PR please?

**Review by Mireille-T — DISMISSED** [review]
Hello @NeroBlackstone , I'm glad to hear you are a native Chinese speaker helping out with the Chinese translations, and thank you so much for correcting my errors. Regarding the issue raised, the translations thus far have not been machine-translated, but since Chinese is my second language (rather than my first, though I did have to study it as an official subject), I fear some of the phrases used are awkward, so I am grateful for your help!

May I also ask why you suggest the usage of 传感器 instead of 感应器? I'm aware that both are translations for "sensors", but I am more used to the latter, so I'm curious to find out if there's a distinction between the two that I am not aware of.

@jimbobbennett This translation is definitely an improvement and includes less awkward phrasing of the expressions, apologies for the mistakes prior to this and I will work on improving my future translations! Just a note before merging, this is still Simplified Chinese and the name should be `README.zh-cn.md`

**Comment by NeroBlackstone** [comment]
> Hello @NeroBlackstone , I'm glad to hear you are a native Chinese speaker helping out with the Chinese translations, and thank you so much for correcting my errors. Regarding the issue raised, the translations thus far have not been machine-translated, but since Chinese is my second language (rather than my first, though I did have to study it as an official subject), I fear some of the phrases used are awkward, so I am grateful for your help!
> 
> May I also ask why you suggest the usage of 传感器 instead of 感应器? I'm aware that both are translations for "sensors", but I am more used to the latter, so I'm curious to find out if there's a distinction between the two that I am not aware of.
> 
> @jimbobbennett This translation is definitely an improvement and includes less awkward phrasing of the expressions, apologies for the mistakes prior to this and I will work on improving my future translations! Just a note before merging, this is still Simplified Chinese and the name should be `README.zh-cn.md`

Hi, @Mireille-T! Thanks for your review.
About translation of "sensors"----“传感器” and "感应器”， these two words are actually synonyms, but  I think "传感器" is more commonly used. If you use Wikipedia search "感应器", it will be redirect to "传感器". 
Thanks all your works before, your translation is good enough as a second language.

**Comment by jimbobbennett** [comment]
Thanks everyone for your contributions. There are conflicts to be resolved, so can you resolve these and I'll merge the PR.

**Comment by NeroBlackstone** [comment]
I must confess that I am not very familiar with git, I think conflic has been resolved.
Thanks review.

**Review by Mireille-T — APPROVED** [review]
Correct me if I'm wrong @jimbobbennett , but I think the conflicts have been resolved, and the PR can be merged. Thanks so much @NeroBlackstone ! 😄

**Review by jimbobbennett — APPROVED** [review]

**Pull request merged**
