### PR TITLE
[ko] Korean translation for 6-consumer lessons 1

### PR DESCRIPTION
**Pull request by WZNT-KimHyeJin**
6-1. : README.ko.md

### CODE REVIEW

**Comment by WZNT-KimHyeJin** [comment]
@jhYun505 @DobiIsFree  please review this file

**Comment by WZNT-KimHyeJin** [comment]
@microsoft-github-policy-service agree

**Comment by DobiIsFree** [comment]
👍Perfect👍

**Comment by jhYun505** [comment]
Good👍

**Comment by WZNT-KimHyeJin** [comment]
@jimbobbennett We have completed the translation of lesson 1's consumer lecture.

**Review by jimbobbennett — APPROVED** [review]

**Comment by jimbobbennett** [comment]
@WZNT-KimHyeJin - can you update this branch from the latest merges to main. I don't seem to have the option here to do it.

**Review by jimbobbennett — APPROVED** [review]

**Pull request merged**
